### ISSUE TITLE
Fix dead link in 3_10_threads

### ISSUE THREAD

**Issue by Hjklvfr** [instrumentisto/rust-incubator#3]
Replace link https://stjepang.github.io/2017/08/13/designing-a-channel.html to
https://github.com/eshikafe/stjepang.github.io/blob/master/_posts/2017-08-13-designing-a-channel.md
![image](https://user-images.githubusercontent.com/34614454/114930223-f33e6880-9e5e-11eb-908e-d2f9e63f32d6.png)

**Comment by tyranron** [comment]
@Hjklvfr thanks!
