### ISSUE TITLE
Alternative solution for "Mutating embedded collection" without mem::replace

### ISSUE THREAD

**Issue by nyanpasu64** [instrumentisto/rust-incubator#4]
## Background

While browsing through the repo, I found the [Mutating embedded collection](https://github.com/instrumentisto/rust-incubator/tree/master/2_idioms/2_2_mem_replace#mutating-embedded-collection) example. I realized that this isn't a fundamental limitation of `&mut`, but instead arises because a closure borrows the entire `&mut self` instead of the fields needed.

There has been some unresolved discussion on changing rustc to only borrow the fields actually used ([Rust pattern: Precise closure capture clauses](http://smallcultfollowing.com/babysteps/blog/2018/04/24/rust-pattern-precise-closure-capture-clauses/)), but I don't know if it will be implemented anytime soon.

In the meantime, the code can be rewritten without `mem::replace`, but I don't know how to add it to the chapter.

```rs
use std::collections::HashSet;

struct Names {
    exclusions: Vec<String>,
    names: HashSet<String>,
}

impl Names {
    fn apply_exclusions(&mut self) {
        let names = &mut self.names;
        self.exclusions.drain(..).for_each(|name| {
            names.remove(&name);
        })
    }
}
```

## Question

How should this solution be incorporated? Including both solutions is probably verbose, only including the current solution fails to teach a more optimal solution, and only including the no-replace solution defeats the purpose of the chapter.

Also I think it's worth mentioning [std::mem::take](https://doc.rust-lang.org/std/mem/fn.take.html) (a convenient shorthand, but semi-recently added, in Rust 1.40 released 2019-12) as well.

**Comment by tyranron** [comment]
@nyanpasu64 hi, thanks for being patient to that!

> only including the current solution fails to teach a more optimal solution, and only including the no-replace solution defeats the purpose of the chapter.

Yeah. The idea of this chapter is neither to resolve "Mutating embedded collection" problem, nor to teach/provide an optional solution for the one. The whole idea is to explain the `mem::replace` and show how it can possible be applicated to different problems. It's not about optimality, but rather about `mem::replace` qualities.

The same approach you may see in other chapters as well. Examples are usually not best-of-class solutions, but rather try to explain some properties and qualities of the described subject.

> How should this solution be incorporated?

If you think this example is rather confusing, I'm open to change it to something better, if you'll come with the one in your mind. But the example should focus on the step's subject and be quite clear about it.

> Also I think it's worth mentioning std::mem::take

Would love a PR 🙃

**Comment by nyanpasu64** [comment]
TBH I don't think I'll be contributing a pull request. I don't have the investment in this project. (I still don't know why this repository is being created, if it's for an organization, event, or wider project which pairs up mentors and students.)

**Comment by tyranron** [comment]
@nyanpasu64 nope, it's nothing like a special project, event or something. We just use it to prepare Rust newcomers on our job, before giving them actual tasks. There is almost nothing done by ourselves, but rather a collection of precious materials and articles done by amazing people. We keep it open, so whoever wants/needs may use it either for himself, or for someone else.

> TBH I don't think I'll be contributing a pull request. I don't have the investment in this project.

No problems 🤷‍♂️  
And thank you for the feedback!
